FileSettings:
    # FileName : "/home/henryi/sft/MaCh3Tutorial/Test.root"
    # FileName: "/home/henryi/sft/MaCh3Tutorial/Test.root"
    # FileName: "/home/henryi/scratch/Delayed_Fit_Long_Chains_no_delay_adapt_0_4.root"
    
    FileName: "/home/henryi/scratch/all_par_chain_without_adaption.root"
    ChainName : "posteriors"

    Verbose : False
    MakeMLModel: True
    RunLLHScan: False
    RunMCMC: False

ParameterSettings:
    ParameterNames : ["sin2th","delm2", "delta", "xsec", "sk", "nd"]
    LabelName : "LogL"
    IgnoredParameters : ["LogL_systematic_xsec_cov", "Log",
                         "LogL_systematic_nddet_cov"]
    ParameterCuts : ["LogL<12345678", "delm2_23>0"]
    CircularParameter: ["delta_cp"]


MLSettings:
    FitterPackage : "TensorFlow"
    FitterName : "Sequential"
    TestSize : 0.2
    MLOutputFile: "tf_model_normal_order.keras"
    PlotOutputName : "tf_tutorial_chain_no.pdf"

    FitterKwargs:
        BuildSettings:
            optimizer: 'adam'
            loss: 'mse'
            metrics: ['mae', 'mse']

        Layers:
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 32
                activation: 'relu'
            - dense:
                units: 16
                activation: 'relu'
            - dense:
                units: 8
                activation: 'relu'

            - dense:
                units: 1
                activation: 'linear'

        FitSettings:
            batch_size: 2048
            epochs: 512

MCMCSettings:
    NSteps: 1000000
    NChains: 1
    UpdateStep: 1000
    BatchSize: 10

    MCMCOutput: "/home/henryi/scratch/tutorial_chain_test.h5"

LikelihoodScanSettings:
    NDivisions: 10000