FileSettings:
    FileName : "/home/henryi/sft/MaCh3Tutorial/Test.root"
    ChainName : "posteriors"
    Verbose : True
    MakeMLModel: True

ParameterSettings:
    ParameterNames : ["sin2th","delm2", "delta", "xsec"]
    LabelName : "LogL"
    IgnoredParameters : ["LogL_systematic_xsec_cov", "LogL_systematic_osc_cov"]
    ParameterCuts : [LogL<12345678] 

MLSettings:
    FitterPackage : "NormalizingFlow"
    FitterName : "realnvp"
    TestSize : 0.6

    FitterKwargs:
      n_iter: 1000
      layer_structure: [8, 64, 64, 1]
      n_layers: 32

    MLOutputName: "flow_model_full.pkl"