FileSettings:
    FileName : "/home/henryi/sft/MaCh3Tutorial/Test.root"
    ChainName : "posteriors"
    Verbose : True
    MakeMLModel: True
    RunLLHScan: True

ParameterSettings:
    ParameterNames : ["sin2th","delm2", "delta", "xsec", "sk", "nd"]
    LabelName : "LogL"
    IgnoredParameters : ["LogL_systematic_xsec_cov", "Log",
                         "LogL_systematic_nddet_cov"]
                        #  , "xsec_4", "sin2th_23",
                        #  "delm2_23", "delta_cp"]
    ParameterCuts : ["LogL<12345678"]


MLSettings:
    FitterPackage : "TensorFlow"
    FitterName : "Sequential"
    TestSize : 0.2
    MLOutputFile: "tf_model_full.keras"
    PlotOutputName : "tf_small_config.pdf"

    FitterKwargs:
        BuildSettings:
            optimizer: 'adam'
            loss: 'mse'
            metrics: ['mae', 'mse']

        Layers:
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dropout:
                rate: 0.1
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dense:
                units: 64
                activation: 'relu'
            - dropout:
                rate: 0.05
            # - dropout:
            #     rate: 0.1
            # - dense:
            #     units: 40
            #     activation: 'relu'
            # - dense:
            #     units: 40
            #     activation: 'relu'
            # - dense:
            #     units: 20
            #     activation: 'relu'
            # - dense:
            #     units: 20
            #     activation: 'relu'
            - dense:
                units: 50
                activation: 'relu'
            - dense:
                units: 25
                activation: 'relu'
            - dense:
                units: 8
                activation: 'relu'

            - dense:
                units: 1
                activation: 'linear'

        FitSettings:
            batch_size: 1000
            epochs: 500


LikelihoodScanSettings:
    xsec_0: [1, 0.7, 1.3] # Norm 0
    xsec_1: [1, 0.5, 1.5] # Norm 
    xsec_2: [1, 0, 2] # Norm 2
    xsec_3: [1.21, 0.0, 1.4] #spline 0
    xsec_4: [1, 0, 3] # Spline 1 
    xsec_5: [0, -10, 15] # Func 0x
    xsec_6: [0, -10, 15] # Func 1
    xsec_7: [0, -10, 15] # Func 2
    xsec_8: [0, -10, 15] # Func 3
    sin2th_12: [0.307, 0.25, 0.35]
    sin2th_23: [0.546, 0.4, 0.7]
    sin2th_13: [0.0220, 0.0, 0.12]
    delm2_12: [0.0000753, 0.00007, 0.00008]
    delm2_23: [0, -0.0026, 0.0026]
    delta_cp: [0, -3.14159, 3.14159]