FileSettings:
    # FileName : "/home/henryi/sft/MaCh3Tutorial/Test.root"
    # FileName: "/home/henryi/scratch/Delayed_Fit_Long_Chains_no_delay_adapt_0_4.root"
    SkipFileLoading: True
    FileName: "/home/henryi/scratch/thinned_partial_chain.root"
    ChainName : "posteriors"
    Verbose : False
    MakeMLModel: True
    RunLLHScan: False
    RunMCMC: True


ParameterSettings:
    ParameterNames : ["sin2th","delm2", "delta", "xsec", "sk", "nd"]
    LabelName : "LogL"
    IgnoredParameters : ["LogL_systematic_xsec_cov", "Log",
                         "LogL_systematic_nddet_cov"]
    ParameterCuts : ["LogL<12345678", "delm2_23>0"]
    CircularParameter: ["delta_cp"]


MLSettings:
    FitterPackage : "TensorFlow"
    FitterName : "sequential"
    TestSize : 0.2

    MLOutputFile: "tf_model_normal_order_small.keras"
    MLScalerOutputName: "scaler_tf_model_normal_order_small.pkl"
    
    PlotOutputName : "tf_normal_order.pdf"
    
    AddFromExternalModel: False
    ExternalModel: "tf_model_normal_order.keras" 
    ExternalScaler: "scaler_tf_model_normal_order_small.pkl"

    FitterKwargs:
        BuildSettings:
            loss: 'mse'
            metrics: ['mae', 'mse']
            learning_rate: 0.01

        Layers:
            # 0
            - dense:
                units: 764
                kernel_regularizer: 0.01
                activation: 'tanh'
            - batchnorm:
                momentum: 0.99
            # 1
            - dense:
                units: 164
                kernel_regularizer: 0.01
                activation: 'relu'
            - batchnorm:
                momentum: 0.99

            # 2
            - dense:
                units: 764
                kernel_regularizer: 0.01
                activation: 'relu'
            - batchnorm:
                momentum: 0.99

            # 3
            - dense:
                units: 1364
                kernel_regularizer: 0.2
                activation: 'relu'
            - batchnorm:
                momentum: 0.99

            # 4
            - dense:
                units: 1764
                kernel_regularizer: 0.01
                activation: 'tanh'
            - batchnorm:
                momentum: 0.99
            # 4
            - dense:
                units: 1764
                kernel_regularizer: 0.01
                activation: 'tanh'
            - batchnorm:
                momentum: 0.99

            # 6
            - dense:
                units: 1
                activation: 'linear'

        FitSettings:
        
            batch_size: 16000
            epochs: 1000
            validation_split: 0.1

MCMCSettings:
    NSteps: 1000000
    NChains: 20
    UpdateStep: 100
    MaxUpdateSteps: 500000

    MCMCOutput: "/home/henryi/scratch/mcmc_chain_GPU.h5"

LikelihoodScanSettings:
    NDivisions: 10000